### ISSUE TITLE
Unable to update plugins - Undefined index: RLuders.Cors

### ISSUE THREAD

**Issue by lucianaelisa** [rluders/oc-cors-plugin#2]
Hi Ricardo! (como vai?) 
When I try update my plugins I get this error message bellow

Undefined index: RLuders.Cors

How can I solve it?

Thanks!

**Comment by rluders** [comment]
Hi @lucianaelisa 

So, I have the same issue here. I'll check and fix it.

Thank you for reporting the issue.

**Comment by rluders** [comment]
OK. It is fixed now, but you will need to remove the plugin and install it again.
